// Final limited comparison/scope checks of previously configured or explicitly declared URLs.
import {readFileSync,writeFileSync,renameSync} from 'node:fs';import {createHash} from 'node:crypto';
import {stableId} from '../../dist/catalog.js';import {fetchXml} from '../../dist/validate.js';import {createHostGate} from '../../dist/host-gate.js';import {auditEndpoint} from '../../dist/audit-check.js';import {normalizeArticleUrl} from '../../dist/article-url.js';import {robotsPolicy} from '../robots-policy.mjs';
const phase=JSON.parse(readFileSync(new URL('checkpoints.json',import.meta.url),'utf8'));const media=phase.results.find(r=>r.name==='Mediazona'),index=media.checked.find(c=>c.observation?.format==='sitemapindex'),url=index.observation.sampleUrls.find(u=>/\/news-sitemap\.xml$/.test(u));if(!url)throw Error('No explicit news sitemap child');const parent=media.resources.find(r=>r.url===index.url&&r.sha256);
const jobs=[{country:'CN',name:'Sixth Tone existing HTTPS comparison',type:'rss',url:'https://www.sixthtone.com/rss/index.xml',kind:'existing_registry_comparison',source_url:'existing_registry',found_at:new Date().toISOString()},
 {country:'RU',name:'Mediazona',type:'sitemap',url,kind:'official_sitemap_index_enumerated_child',source_url:index.url,found_at:parent.checked_at,page_sha256:parent.sha256},
 {country:'ZA',name:'GroundUp path-scope confirmation',type:'sitemap',url:'https://groundup.org.za/sitemap.xml',kind:'already_checked_scope_review'},
 {country:'BR',name:'Brasil de Fato path-scope confirmation',type:'sitemap',url:'https://www.brasildefato.com.br/sitemap.xml',kind:'already_checked_scope_review'}];
const baseGate=createHostGate(2000);let requests=0;const gate=async(h,d)=>{if(requests>=20)throw Error('TARGETED_BUDGET');requests++;return baseGate(h,d);};const results=[];
for(const job of jobs){const robotUrl=new URL('/robots.txt',job.url).href;let access_review;try{const r=await fetchXml(robotUrl,12000,1024*1024,gate);access_review={robots_url:robotUrl,http_status:r.status,checked_at:new Date().toISOString(),...(r.status===200?robotsPolicy(r.body.toString(),job.url):{decision:[404,410].includes(r.status)?'allowed_robots_absent':'unknown',matched_rule:null})};}catch(e){access_review={robots_url:robotUrl,decision:'unknown',reason:e.code??e.message};}
 if(!['allowed','allowed_robots_absent'].includes(access_review.decision)){results.push({...job,access_review,skipped:'ROBOTS_UNAVAILABLE'});continue;}
 const endpoint={id:stableId('ep',[job.type,job.url]),type:job.type,url:job.url},raw=await auditEndpoint(endpoint,gate,true),{observedUrls,...observation}=raw,urls=observedUrls??[],unique=[...new Set(urls.map(u=>normalizeArticleUrl(u)).filter(u=>u.kind==='candidate').map(u=>u.url))].sort();
 const path_scope={total_urls:urls.length,article_path_prefix:urls.filter(u=>new URL(u).pathname.startsWith('/article/')).length,dated_path:urls.filter(u=>/\/20\d\d\/\d\d\/\d\d\//.test(new URL(u).pathname)).length,home_or_known_navigation:urls.filter(u=>normalizeArticleUrl(u).kind==='uncertain').length};
 results.push({...job,endpoint_id:endpoint.id,access_review,observation,parsed_unique_candidate_urls:unique.length,url_set_sha256:createHash('sha256').update(JSON.stringify(unique)).digest('hex'),path_scope});console.log(JSON.stringify({name:job.name,status:observation.auditStatus,count:observation.entriesWithUrl,final:observation.finalUrl,scope:path_scope,requests}));
 const path=new URL('targeted.json',import.meta.url),temp=new URL(path.href+'.tmp');writeFileSync(temp,JSON.stringify({request_budget:20,governed_attempts:requests,no_registry_mutation:true,results},null,2)+'\n');renameSync(temp,path);
}
