import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,cpSync,writeFileSync,readFileSync,symlinkSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {ActivityLedger} from '../dist/activity-ledger.js';
import {normalizeRegistry} from '../dist/catalog.js';
const raw={countries:[{code:'US',name:'USA',feeds:[{name:'Paused',url:'https://paused.example/rss'},{name:'Ready',url:'https://ready.example/rss'}]}]},catalog=normalizeRegistry(raw),paused=catalog.sources.find(s=>s.name==='Paused'),ready=catalog.sources.find(s=>s.name==='Ready');
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'recovery-cli-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));cpSync(new URL('../dist/',import.meta.url),join(dir,'dist'),{recursive:true});mkdirSync(join(dir,'scripts'));cpSync(new URL('../scripts/collect-activity.mjs',import.meta.url),join(dir,'scripts/collect-activity.mjs'));symlinkSync(new URL('../node_modules/',import.meta.url).pathname,join(dir,'node_modules'),'dir');writeFileSync(join(dir,'package.json'),'{"type":"module"}');const db=join(dir,'test.sqlite'),l=new ActivityLedger(db),at=new Date(Date.now()-5000).toISOString();l.syncRegistry(catalog,at);l.acquire('fixture',at,3600);l.commit({id:'initial-blocked',endpoint:paused.endpoints[0],checked_at:at,status:'blocked',format:null,reason:'HTTP_403',urls:[],traffic:'inspection',http_status:403,attempts:1},[paused],'fixture',at);l.release('fixture');l.close();return{dir,db,at};}
function run(f,code,env={}){const result=spawnSync(process.execPath,['--experimental-test-module-mocks','--input-type=module','--eval',code],{cwd:f.dir,env:{PATH:process.env.PATH,WNS_ACTIVITY_DB:f.db,...env},encoding:'utf8',timeout:10000});assert.equal(result.status,0,result.stderr+'\n'+result.stdout);return result;}
const prelude=`import {mock} from 'node:test';import {pathToFileURL} from 'node:url';import {join} from 'node:path';const raw=${JSON.stringify(raw)};const {normalizeRegistry}=await import('./dist/catalog.js');const catalog=normalizeRegistry(raw);mock.module(pathToFileURL(join(process.cwd(),'dist/config.js')).href,{namedExports:{loadData:()=>({catalog})}});`;
test('daily CLI honors review pause even with --force, persists one transient attempt and preserves old collection',t=>{
 const f=fixture(t),result=run(f,prelude+`let calls=0;mock.module(pathToFileURL(join(process.cwd(),'dist/audit-check.js')).href,{namedExports:{auditEndpoint:async e=>{if(e.url.includes('paused')||++calls>1)throw Error('unexpected request/retry');return{endpointId:e.id,type:e.type,url:e.url,checkedAt:new Date().toISOString(),outcome:'unhealthy',httpStatus:503,reason:'HTTP_503',format:null,auditStatus:'http_error',attempts:1};}}});process.argv=[process.execPath,'collector','--inspection','--db',process.env.WNS_ACTIVITY_DB,'--force','--limit','2'];await import('./scripts/collect-activity.mjs');console.log('REQUESTS='+calls);`);
 assert.ok(result.stdout.includes('REQUESTS=1'));const deferred=JSON.parse(readFileSync(join(f.dir,'activity/recovery-deferred.json')));assert.equal(deferred.deferred.length,1);assert.equal(deferred.deferred[0].endpoint_id,paused.endpoints[0].id);const l=new ActivityLedger(f.db);assert.equal(l.db.prepare('select count(*) n from collections').get().n,2);assert.equal(l.db.prepare('select reason from collections where id=?').get('initial-blocked').reason,'HTTP_403');assert.equal(l.recovery.state(ready.endpoints[0].id).http_status,503);assert.equal(l.recovery.state(ready.endpoints[0].id).attempts,1);assert.equal(l.db.prepare('select baseline_at from bindings where source_id=?').get(ready.id).baseline_at,null);assert.equal(l.db.prepare('select enabled from registry where source_id=?').get(paused.id).enabled,1);l.close();
});
test('weekly CLI skips paused endpoint, preserves its cached diagnosis and does not advance completed-full-audit timestamp',t=>{
 const f=fixture(t);mkdirSync(join(f.dir,'audits'));const oldAt='2026-09-30T20:05:37.106Z',old={endpointId:paused.endpoints[0].id,type:'rss',url:paused.endpoints[0].url,checkedAt:oldAt,outcome:'unhealthy',httpStatus:403,reason:'HTTP_403',format:null,auditStatus:'blocked'};writeFileSync(join(f.dir,'audits/health-latest.json'),JSON.stringify({version:1,audit:{runId:'previous',startedAt:oldAt,finishedAt:oldAt,total:2,checked:2,skipped:0,lastCompletedFullAuditAt:oldAt,statuses:{}},observations:[old]}));
 run(f,prelude+`mock.module(pathToFileURL(join(process.cwd(),'dist/audit-check.js')).href,{namedExports:{auditEndpoint:async e=>{if(e.url.includes('paused'))throw Error('paused endpoint fetched');return{endpointId:e.id,type:e.type,url:e.url,checkedAt:new Date().toISOString(),outcome:'healthy',httpStatus:200,reason:null,format:'rss',auditStatus:'valid_empty',attempts:1,entryCount:0};}}});process.argv=[process.execPath,'audit','2026-10-02-fixture'];await import('./dist/audit.js');`);
 const h=JSON.parse(readFileSync(join(f.dir,'audits/health-latest.json')));assert.equal(h.audit.checked,1);assert.equal(h.audit.skipped,1);assert.equal(h.audit.lastCompletedFullAuditAt,oldAt);assert.deepEqual(h.observations.find(x=>x.endpointId===old.endpointId),old);assert.ok(h.observations.some(x=>x.endpointId===ready.endpoints[0].id));const l=new ActivityLedger(f.db);assert.equal(l.db.prepare('select count(*) n from collections').get().n,1);l.close();
});
test('weekly shared-budget exhaustion is explicit partial coverage, with no network attempt or full-audit advance',t=>{
 const f=fixture(t),l=new ActivityLedger(f.db);l.db.prepare('INSERT INTO request_budget VALUES(?,?)').run(new Date().toISOString().slice(0,10),12000);l.close();mkdirSync(join(f.dir,'audits'));const oldAt='2026-09-30T20:05:37.106Z';writeFileSync(join(f.dir,'audits/health-latest.json'),JSON.stringify({version:1,audit:{runId:'previous',startedAt:oldAt,finishedAt:oldAt,total:2,checked:2,skipped:0,lastCompletedFullAuditAt:oldAt,statuses:{}},observations:[]}));
 run(f,prelude+`mock.module(pathToFileURL(join(process.cwd(),'dist/audit-check.js')).href,{namedExports:{auditEndpoint:async()=>{throw Error('quota-exhausted endpoint fetched');}}});process.argv=[process.execPath,'audit','2026-10-02-budget'];await import('./dist/audit.js');`);
 const h=JSON.parse(readFileSync(join(f.dir,'audits/health-latest.json'))),report=JSON.parse(readFileSync(join(f.dir,'audits/2026-10-02-budget/report.json')));assert.equal(h.audit.checked,0);assert.equal(h.audit.skipped,2);assert.equal(h.audit.lastCompletedFullAuditAt,oldAt);assert.ok(report.endpoints.some(x=>x.incomplete_reason==='DAILY_REQUEST_BUDGET_EXHAUSTED'));
});
test('unexpected operational failure never publishes a completed weekly audit',t=>{
 const f=fixture(t);const code=prelude+`mock.module(pathToFileURL(join(process.cwd(),'dist/audit-check.js')).href,{namedExports:{auditEndpoint:async()=>{throw Error('fixture operational failure');}}});process.argv=[process.execPath,'audit','2026-10-02-failure'];await import('./dist/audit.js');`;
 const result=spawnSync(process.execPath,['--experimental-test-module-mocks','--input-type=module','--eval',code],{cwd:f.dir,env:{PATH:process.env.PATH,WNS_ACTIVITY_DB:f.db},encoding:'utf8',timeout:10000});assert.notEqual(result.status,0);const report=JSON.parse(readFileSync(join(f.dir,'audits/2026-10-02-failure/report.json')));assert.equal(report.audit.finishedAt,null);assert.equal(report.audit.lastCompletedFullAuditAt,null);
});
